install.packages("PROJ", dependencies = TRUE)
install.packages("sf", dependencies = TRUE)
install.packages("opendatatoronto", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("systemfonts", dependencies = TRUE)
install.packages("textshaping", dependencies = TRUE)
install.packages("svglite", dependencies = TRUE)
install.packages("ragg", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
unique(data$`Age Group`)
